[profile.default]
src = "Challenge"
out = "out"
libs = ["lib"]

[rpc_endpoints]
scroll = "https://scroll-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
scrollSepolia="https://scroll-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
